# Задача 1
1. Скачать данные по ссылке: https://www.kaggle.com/datasets/ionaskel/laptop-prices.
2. Считать данные с помощью pandas.
3. Вывести на экран первые 5 строк.
4. Посмотреть на описание признаков и на их содержание.

In [54]:
import pandas as pd
import numpy as np
df = pd.read_csv('laptop_price.csv', sep = ',', encoding = 'windows-1251')
df.head()

## 1.1
Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU.

In [ ]:
df['Cpu_Company'] = df['Cpu'].apply(lambda x: x.split(' ')[0])
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

In [ ]:
df['Cpu_Company'].value_counts()

Cpu_Company
Intel      1240
AMD          62
Samsung       1
Name: count, dtype: int64

## 1.2
Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя.

In [ ]:
def get_memory_amount(memory):
    memory_amount = memory.split(' ')[0]
    if memory_amount.endswith('GB'):
        memory_amount = float(memory_amount[:-2])
    elif memory_amount.endswith('TB'):
        memory_amount = float(memory_amount[:-2]) * 1024
    return memory_amount

df['Memory_Amount'] = df['Memory'].apply(get_memory_amount)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128.0
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128.0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256.0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512.0
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256.0

In [ ]:
df['Memory_Amount'].value_counts()

Memory_Amount
256.0     508
1024.0    250
128.0     177
512.0     140
500.0     132
32.0       45
64.0       17
2048.0     16
16.0       10
180.0       5
240.0       1
8.0         1
508.0       1
Name: count, dtype: int64

## 1.3
Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.).

In [ ]:
df['Memory_Type'] = df['Memory'].apply(lambda x: x.split(' ')[1])
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128.0,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128.0,Flash
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256.0,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512.0,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256.0,SSD

In [ ]:
df['Memory_Type'].value_counts()

Memory_Type
SSD       843
HDD       375
Flash      75
Hybrid     10
Name: count, dtype: int64

## 1.4
Удалите признаки Memory и ScreenResolution.

In [ ]:
df.drop(columns = ['Memory', 'ScreenResolution'], inplace = True)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128.0,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128.0,Flash
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256.0,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512.0,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256.0,SSD

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   laptop_ID      1303 non-null   int64
 1   Company        1303 non-null   object
 2   Product        1303 non-null   object
 3   TypeName       1303 non-null   object
 4   Inches         1303 non-null   float64
 5   Cpu            1303 non-null   object
 6   Ram            1303 non-null   object
 7   Gpu            1303 non-null   object
 8   OpSys          1303 non-null   object
 9   Weight         1303 non-null   object
 10  Price_euros    1303 non-null   float64
 11  Cpu_Company    1303 non-null   object
 12  Memory_Amount  1303 non-null   float64
 13  Memory_Type    1303 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 142.6+ KB

# Задача 2

## 2.1
Создайте признак SSD, который изначально равен 0.

In [ ]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128.0,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128.0,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256.0,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512.0,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256.0,SSD,0

## 2.2
Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD.

In [ ]:
df.loc[df['Memory_Type'] == 'SSD', 'SSD'] = 1
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128.0,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128.0,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256.0,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512.0,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256.0,SSD,1

## 2.3
Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный.

In [ ]:
df['Weight'] = df['Weight'].str.replace('kg', '').astype('float')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128.0,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128.0,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256.0,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512.0,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256.0,SSD,1

In [ ]:
df['Weight'].dtype

dtype('float64')

# Задача 3
Создайте датафрейм с клиентами:

In [ ]:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})
clients

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

## 3.1
Присоедините к таблице clients данные по ноутбукам через метод join.

In [ ]:
clients_laptops = clients.set_index('laptop_id')
clients_laptops

           client_id
laptop_id
506               45
398               32
710               67
120               33
1999              43

In [ ]:
df_laptops = df.set_index('laptop_ID')
df_laptops

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
laptop_ID,,,,,,,,,,,,,,
1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128.0,SSD,1
2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128.0,Flash,0
3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256.0,SSD,1
4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512.0,SSD,1
5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256.0,SSD,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Intel Core i7 6500U 2.5GHz,4GB,Intel HD Graphics 520,Windows 10,1.80,638.00,Intel,128.0,SSD,1
1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.30,1499.00,Intel,512.0,SSD,1
1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Intel Celeron Dual Core N3050 1.6GHz,2GB,Intel HD Graphics,Windows 10,1.50,229.00,Intel,64.0,Flash,0
1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Intel Core i7 6500U 2.5GHz,6GB,AMD Radeon R5 M330,Windows 10,2.19,764.00,Intel,1024.0,HDD,0
1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,Intel Celeron Dual Core N3050 1.6GHz,4GB,Intel HD Graphics,Windows 10,2.20,369.00,Intel,500.0,HDD,0

In [ ]:
clients_df_joined = clients_laptops.join(df_laptops).reset_index()
clients_df_joined

,laptop_id,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,506,45,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256.0,SSD,1.0
1,398,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,710,67,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024.0,HDD,0.0
3,120,33,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,256.0,SSD,1.0
4,1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3.2
Присоедините к таблице clients данные по ноутбукам через метод merge.

In [ ]:
clients_df_merged1 = clients.merge(df, left_on = 'laptop_id', right_on = 'laptop_ID')
clients_df_merged1

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,45,506,506,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256.0,SSD,1
1,67,710,710,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024.0,HDD,0
2,33,120,120,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,256.0,SSD,1

In [ ]:
clients_df_merged2 = df.merge(clients, left_on = 'laptop_ID', right_on = 'laptop_id')
clients_df_merged2

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,client_id,laptop_id
0,120,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,256.0,SSD,1,33,120
1,506,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256.0,SSD,1,45,506
2,710,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024.0,HDD,0,67,710

# Задача 4
Составьте несколько сводных таблиц.

## 4.1
Найдите среднюю стоимость ноутбуков в зависимости от компании-производителя.

Отсортируйте от меньшей стоимости к большей.

In [ ]:
df.groupby('Company').agg({'Price_euros': 'mean'}).sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

## 4.2
Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора.

In [ ]:
df.groupby('Cpu_Company').agg({'Price_euros': ['min', 'mean', 'max']})

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Intel             174.0  1152.214145  6099.0
Samsung           659.0   659.000000   659.0

## 4.3
Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ.

In [ ]:
pd.crosstab(index = df['Cpu_Company'], 
            columns = df['Ram'])

Ram          12GB  16GB  24GB  2GB  32GB  4GB  64GB  6GB  8GB
Cpu_Company
AMD             2     3     0    1     0   31     0   13   12
Intel          23   197     3   21    17  343     1   28  607
Samsung         0     0     0    0     0    1     0    0    0

## 4.4
Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти.

In [ ]:
df.pivot_table(index = 'Ram', 
                columns = 'OpSys', 
                values = 'Price_euros', 
                aggfunc = 'mean', 
                margins = True, 
                margins_name = 'Total')

OpSys,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS,Total
Ram,,,,,,,,,,
12GB,NaN,NaN,949.000000,NaN,NaN,1205.998261,NaN,2299.000000,NaN,1239.438400
16GB,NaN,2199.000000,974.000000,2139.970000,1265.316667,1916.548315,2589.0000,2840.400000,2611.806667,1936.771150
24GB,NaN,NaN,NaN,NaN,NaN,2206.333333,NaN,NaN,NaN,2206.333333
2GB,NaN,234.333333,NaN,NaN,NaN,257.534211,NaN,NaN,NaN,254.370455
32GB,NaN,NaN,NaN,NaN,NaN,3413.085882,NaN,NaN,NaN,3413.085882
4GB,434.0,397.726316,417.705625,959.000000,393.980625,604.317509,673.9975,1036.020833,NaN,574.572480
64GB,NaN,NaN,NaN,NaN,NaN,3975.000000,NaN,NaN,NaN,3975.000000
6GB,NaN,NaN,NaN,NaN,NaN,615.206341,NaN,NaN,NaN,615.206341
8GB,NaN,1122.000000,814.618148,1167.333333,722.674516,1190.119217,1668.9500,1739.483704,1490.978000,1180.812940
Total,434.0,553.585185,617.068871,1262.871250,587.973333,1168.139478,1286.4800,1686.651333,1749.630769,1123.686992